return function()
	describe("TestA", function()
		it("should pass", function()
			expect(true).to.be.ok()
		end)
	end)
	describe("TestB", function()
		it("should fail", function()
			expect(false).to.equal(true)
		end)
	end)
	describe("TestC", function()
		itSKIP("should skip", function()
			expect(true).to.be.ok()
		end)
	end)
end
