return function()
	describe("Test1", function()
		it("should pass", function()
			expect(true).to.be.ok()
		end)
	end)
	describe("Test2", function()
		it("should pass", function()
			expect(true).to.be.ok()
		end)
		it("should also pass", function()
			expect(true).to.be.ok()
		end)
	end)
	describe("Test3", function()
		it("should pass", function()
			expect(true).to.be.ok()
		end)
		itSKIP("should skip", function()
			expect(true).to.be.ok()
		end)
	end)
end
